// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGfDvWQcDJ0Mwx8ZUFGrqT3gzKDslCaeU',
    appId: '1:74930175009:android:b9dcfbc19f2ccbc341b760',
    messagingSenderId: '74930175009',
    projectId: 'idsc-37551',
    databaseURL: 'https://idsc-37551.firebaseio.com',
    storageBucket: 'idsc-37551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9AxUm0o8zZ8kt7f7VkH5r66R18sbnlk0',
    appId: '1:74930175009:ios:783cd7a01d2b92f741b760',
    messagingSenderId: '74930175009',
    projectId: 'idsc-37551',
    databaseURL: 'https://idsc-37551.firebaseio.com',
    storageBucket: 'idsc-37551.appspot.com',
    iosClientId: '74930175009-dnk8kj42duukur8sbpjgdp5lf5mouk09.apps.googleusercontent.com',
    iosBundleId: 'cabinet.gov.eg',
  );
}
